### PR TITLE
News app added

### PR DESCRIPTION
**Pull request by RiyaGupta89**
# I have added the news react app.

## Resolves issue #262

news

### CODE REVIEW

**Comment by RiyaGupta89** [comment]
@harshita2216 I need your help. I added my code in the main branch without creating a seperate branch for my project. My bad. But at the same time somebody made changes in the main branch too and that resulted in conflict. Sorry, please help me solve it.

**Comment by harshita2216** [comment]
Make the PR, I'll resolve the conflicts. @RiyaGupta89

**Comment by RiyaGupta89** [comment]
@harshita2216 I have already made the PR

**Comment by harshita2216** [comment]
> @harshita2216 I have already made the PR

That is the PR for fork update. Make a PR to Ayush's repo.

**Comment by harshita2216** [comment]
> > @harshita2216 I have already made the PR
> 
> That is the PR for fork update. Make a PR to Ayush's repo.

Okay, you've made it there now! Looking into it.

**Pull request merged**
